MySite/MySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('blog-external/', include('scrapey.urls', namespace='scrapey')),
    path('manage/', admin.site.urls),
    path('api/', include('api.urls', namespace='api'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySite/api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'api'

# router = routers.DefaultRouter()
# router.register(r'blog-external', views.PostViewSet, basename='blog-external')
# router.register(r'blogposts', views.BlogPostViewSet)

urlpatterns = [
    path('blog-list/', views.blog_list),
    path('blog-external-list/', views.blog_external_list),
    path('blog-external-list/most-recent/', views.blog_external_most_recent)
]

urlpatterns = format_suffix_patterns(urlpatterns)

# urlpatterns = [
#     path('blog-posts/', views.BlogPostList.as_view()),
#     path('blog-posts/most_recent_post', views.BlogPostList.as_view())
# ]

MySite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.post_list, name='post_list' ),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail' ),
    path('books/', views.book_list, name='book_list'),
    path('books/<int:year>/<int:month>/<int:day>/<slug:post>/', views.book_detail, name='book_detail'),
    path('knowledge-repo/', views.knowledge_repo,  name='knowledge_repo'),
    path('Questions/', views.question, name='questions'),
    path('', views.home, name='blog-home' ),
    ]

MySite/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager



class PostBase(models.Model):
    """Generic post class that Book, Blog, and Program post can inherit from"""
    post_title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, unique_for_date='created') # I think this helps to make url strings
    post_body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateField(auto_now=True)
    display = models.BooleanField(default=True)

    class Meta:
        # abstract = True
        ordering = ('-created',)


class BlogPost(PostBase):
    """Class to model a blog post. """
    
    # I do not need any specific fields for blog post. And meta ordering is taken care of in PostBase as well


    def __str__(self):
        """This is what shows up in admin page"""
        return self.post_title


    def get_absolute_url(self):
        """Retrieve the absolute url for a post"""
        # I do not understand how this works.
        return reverse('blog:post_detail',
                       args=[self.created.year,
                             self.created.month,
                             self.created.day,
                             self.slug])


class Book(PostBase):
    """Class to model book data"""
    book_title = models.CharField(max_length=300)    
    author = models.CharField(max_length=300)
    blog_display = models.BooleanField(default=False)
    cover_image = models.ImageField(default='Nothing_Yet', upload_to='book_images/')


    def __str__(self):
        """This is what shows up in admin page"""
        return self.book_title


    def get_author(self):
        """Author text is stored like "Last; First" But causes an error if a comma is used instead for storage"""
        try:
            named_reversed = self.author.split(';')
            name_normal = named_reversed[1].strip() + ' ' + named_reversed[0].strip()
        except:
            name_normal = 'Author Error'
        
        return name_normal


    def get_absolute_url(self):
        """Retrieve the absolute url for a book detail"""

        return reverse('blog:book_detail',
                       args=[self.created.year,
                             self.created.month,
                             self.created.day,
                             self.slug])


class Comment(models.Model):
    """Comments on posts"""
    post = models.ForeignKey(PostBase, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) # This field will allow admins to hide inappropriate comments

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


class Knowledge(models.Model):
    """Class to model a knowledge record"""

    author = models.CharField(max_length=500)
    description = models.TextField()
    source = models.TextField()
    tags = models.TextField(default='Placeholder')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def tags_as_list(self):
        try:
            return self.tags.split(';')
        except:
            return ['Error']


class Question(models.Model):
    """Represents a question for my questions page"""
    
    question = models.TextField()
    category = models.TextField(default='Uncategorized') 

MySite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost, Book, Comment, Knowledge, Question
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Q
from .data import data_import, data_export




# print('http://127.0.0.1:8000/knowledge-repo')
print('http://127.0.0.1:8000')
print('http://127.0.0.1:8000/manage')
# print('http://127.0.0.1:8000/blog')
# print('http://127.0.0.1:8000/books')
# print('http://127.0.0.1:8000/visuals')



def home(request):
    """Renders the home page. """


    return render(request,'blog/index.html')


def post_list(request):
    """Displays the posts."""

    blog_posts = BlogPost.objects.all()
    books = Book.objects.exclude(blog_display=False)

    posts_and_books = list(blog_posts) + list(books)
    posts_and_books.sort(reverse=True, key=lambda model: model.created)

    # Below loop creates a new list containing tuples for each post with the second tuple index containing the post type
    # such as 'Post' or 'Book'
    all_posts = []
    for i in range(len(posts_and_books)):
        all_posts.append((posts_and_books[i], posts_and_books[i].__class__.__name__))

    paginator = Paginator(all_posts, 7) 
    page = request.GET.get('page') # Look at paginator template to see how this value would be set.
   
    try:
        all_posts = paginator.page(page)
    except PageNotAnInteger:
        # If the page is not an integer then deliver the first page.
        all_posts = paginator.page(1)
    except EmptyPage:
        # If the page is out of range deliver the last page of results.
        all_posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'all_posts': all_posts})


def post_detail(request, year, month, day, post):
    """Single Post"""

    # Below method raises an exception if the post is not found based on the url inputs provided.
    post = get_object_or_404(BlogPost, slug=post,                                  
                                   created__year=year, 
                                   created__month=month,
                                   created__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True) 
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object but don't commit it to the database yet so you can link it to the post
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            new_comment = True
    else:
        comment_form = CommentForm()

    return render(request, 'blog/post/detail.html',
                 {'post': post,
                 'comments': comments,
                 'new_comment': new_comment,
                 'comment_form': comment_form})




def book_list(request):
    """Renders the generic book list view"""

    books = Book.objects.order_by('-created')  
    return render(request, 'blog/book/list.html', {'books': books})
    

def book_detail(request, year, month, day, post):
    """Single Book"""

    # Below method raises an exception if the post is not found based on the url inputs provided.
    book_post = get_object_or_404(Book, slug=post,                                  
                                   created__year=year, 
                                   created__month=month,
                                   created__day=day)

    # List of active comments for this post
    comments = book_post.comments.filter(active=True) 
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object but don't commit it to the database yet so you can link it to the post
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = book_post
            # Save the comment to the database
            new_comment.save()
            new_comment = True
    else:
        comment_form = CommentForm()

    return render(request, 'blog/book/detail.html',
                 {'book_post': book_post,
                 'comments': comments,
                 'new_comment': new_comment,
                 'comment_form': comment_form})

    



def knowledge_repo(request):
    """Produces the beautiful table of learning"""


    try:
        search_term = request.GET['search_box']
    except:
        search_term = ''

    if search_term == '':
        knowledge_list = Knowledge.objects.all()
    else:
        knowledge_list = Knowledge.objects.filter(Q(author__icontains=search_term) | Q(description__icontains=search_term)| Q(tags__icontains=search_term))


    return render(request, 'blog/knowledge_repo.html', {'knowledge_list': knowledge_list})



def question(request):
    """Render the question page"""
    questions = Question.objects.all()
    return render(request,'blog/questions.html', context={'questions': questions})



# def data_play(request):
#     """lolol"""
    
#     if request.method == 'POST':
#         #Depending on what button you click you will performa a different action

#         # First three are exporting of different data
#         if request.POST.get('Book'):            
#             data_export.export_db(Book)
#         elif request.POST.get('sql_import'):            
#             data_import.import_sql()
#         elif request.POST.get('Blog'):
#             data_export.export_db(Post)
#         elif request.POST.get('Knowledge'):
#             data_export.export_db(Knowledge)
#         elif request.POST.get('knowledge_import'):
#             data_import.import_knowledge()
#         elif request.POST.get('book_import'):
#             data_import.import_books()
#         elif request.POST.get('knowledge_update'):
#             data_import.update_knowledge()
#         elif request.POST.get('update_book'):
#             data_import.update_books()
#         elif request.POST.get('blog_update'):
#             data_import.import_blog()
            

#     return render(request, 'blog/data_import.html')

# def post_share(request, post_id):
#     """Sharing a post via email. This view handles both the processing of get request and post.
#     Currently there is no link on blog detail page to get to this. Need to fiddle with email stuff more first."""

#     post = get_object_or_404(Post, id=post_id)
#     sent = False

#     if request.method =='POST':
#         form = EmailPostForm(request.POST)
#         if form.is_valid():
#             form_data = form.cleaned_data
#             post_url = request.build_absolute_uri(
#                 post.get_absolute_url())
#             subject = f"Yo. {form_data['name']} thinks you should read this post: {post.title}"
#             message = f"Read that shit at {post_url} \n\n My comments: {form_data['comments']}" # I have not tested after adding this line yet
#             send_mail(subject, message, 'brandtgreen97@gmail.com', [form_data['to']])
#             sent = True
#     else:
#         form = EmailPostForm()

#     return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

MySite/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog.css' %}" />
    {% block styles %}{% endblock %}

    <link rel="icon" href="{% static 'blog/Images/BlackHole.jpg' %}" />

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark" style="margin-bottom: 0px !important;">
            <div class="container">
                <a class="navbar-brand" href="/" style="color: white !important;">
                    <h3>FunWithBrandt</h3>
                  </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 navbar-right justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link"  href="{% url 'blog:blog-home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/books/">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/knowledge-repo/">Knowledge-Repository</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:questions' %}">Questions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/blog-external/">Blog-External</a>
                        </li>
                        <!-- <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" class="nav-link dropdown-toggle" data-toggle="dropdown" href="/visuals/" role="button" aria-haspopup="true" aria-expanded="false">Visuals</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="/visuals/">Action</a>
                                <a class="dropdown-item" href="/visuals/">Another action</a>
                                <a class="dropdown-item" href="/visuals/">Something else here</a>
                              </div>
                        </li> -->
                        <!-- <li class="nav-item">
                            <a class="nav-link" href="/manage/">Admin</a>
                        </li> -->
                    </ul>
                    <!-- <form class="form-inline">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form> -->
                </div>
            </div>        
        </nav>

    </header>

    {% block nav_extension %} {% endblock nav_extension %}

    <div class="container body-content">
        <main class="pb-3">
            {% block content %}{% endblock %}
        </main>
        
    </div>


    <footer class="border-top footer">
        <div id="footer-head" ></div>
        <div id="footer-body" class="container">
            &copy; 2020 - FunWithBrandt
        </div>
    </footer>

    <script src="{% static "blog/js/jquery/jquery.min.js" %}"></script>  
    <!-- I think popper thing below make actually be included in bootstramp min js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static "blog/js/bootstrap/bootstrap.bundle.min.js" %}"></script>

    {% block scripts %}{% endblock %} {# This allows for other scripts on extended pages#}


</body>
</html>

MySite/blog/templates/blog/data_import.html
{% extends "blog/base.html" %}

{% block title %}Data{% endblock %}

{% block content %}
     <h1>Data Importing </h1>
     <br /><br />
           


    <div class="row">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
             {# Could instead use one book name and different values to differentiate on back end? #}    
            <div class="row">
                <div class="col">
                    <div class="btn-group">
                        <button type="submit" value="Book" name="Book" class="btn btn-primary">Export Book</button><br /><br />
                        <button type="submit" value="Blog" name="Blog" class="btn btn-info">Export Blog</button><br /><br />
                        <button type="submit" value="Knowledge" name="Knowledge" class="btn btn-secondary">Export Knowledge</button>       
                    </div>
                </div>

                <div class="col">
                    <div {#class="col"#}>
                        <button type="submit" value="blog_update" name="blog_update" class="btn btn-primary">Import Blog</button><br /><br />
                        <button type="submit" value="book_import" name="book_import" class="btn btn-primary">Import Book</button><br /><br />
                        <button type="submit" value="update_book" name="update_book" class="btn btn-primary">Update Book</button><br /><br />
                        <button type="submit" value="knowledge_import" name="knowledge_import" class="btn btn-primary">Import Knowledge</button>        
                        <button type="submit" value="sql_import" name="sql_import" class="btn btn-primary">sql_import</button><br /><br />
                    </div>
                </div>
            </div>

        </form>  
    </div>








    {% comment %}

     <div class="col">
                         
                    <button type="submit" value="book_import" name="book_import" class="btn btn-primary">Import Books</button> 
                    <button type="submit" value="knowledge_update" name="knowledge_update" class="btn btn-primary">Update Knowledge</button>   
    </div>


    <p>Below is supposed to be a python console that you can use to play around with, but it has been fickle for me in the
        past so I apologize if it is not working.    
    </p>
    <iframe style="width: 640; height: 480; border-style:solid;" name="embedded_python_anywhere" src="https://www.pythonanywhere.com/embedded3/"></iframe>
    {% endcomment %}

    <br /><br /><br /><br />




{% endblock %}

MySite/blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %}FunWithBrandt-Home{% endblock %}

{% block styles %}
    <style>
        #explore-head {
            margin-bottom: 25px;
        }

        #explore-col {
            margin-bottom: 10px;
        }
    </style>
{% endblock styles %}


{% block nav_extension %}
    <h1 class="text-center sticky-top shadow-lg" style="background-color: grey; width: 100%; opacity: .9;">Welcome</h1>
    
{% endblock nav_extension %}

{% block content %}
    <div>
        <div class="d-flex justify-content-center">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <!-- <li data-target="#carouselExampleIndicators" data-slide-to="2"></li> -->
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="../../static/blog/Images/lsuGraduation.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="../../static/blog/Images/smartLabCFA2.jpg" class="d-block w-100" alt="...">
                    </div>
                    <!-- <div class="carousel-item">
                        <img src="../../static/blog/Images/The Boys2.jpg" class="d-block w-100" alt="...">
                    </div> -->
                </div>

                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>


    <br>
    <div class="row justify-content-center">
        <div class="col-md-9">
            <p>This site is just a place where I can share my thoughts and
                display any fun projects I am working on. I built the site with 
                <a href="https://www.djangoproject.com/">Django</a>, which is a Python Web Framework
                used to build websites. There are some other big websites like <a href="https://www.pinterest.com/">Pinterest</a> 
                and <a href="https://www.instagram.com/">Instagram</a> that are also built with Django so it's a
                pretty neat tool that's good for both small projects and large scale operations. If you are curious 
                you can see the code used to make this site in my <a href="https://github.com/Brandt-moreThan4/MySite">GitHub repository.</a>
            </p>
            <p>
                If you have suggestions for anything on the site, notice any typos, or 
                you just want to tell me how handsome I am, I would love some communication.
                My email is: <a href="mailto:153144green@chsbr.net">153144green@chsbr.net</a>. I am eagerly awaiting
                to hear from you.
            </p>
        </div>
    </div>


    <br><br><hr>

    <div class="row">
        <div id="explore-head" class="text-center col">
            <h3>What are you looking for?</h3>
        </div>
    </div>
    <br>
    <div class="row">
        <div id="explore-col" class="col-md-4">
            <a href="{% url  'blog:post_list' %}"><h3>Blog</h3></a> 
                <p>If you are interested in reading my incredibly profound and insightful thoughts on random topics
                    then you should go to my <a href="{% url 'blog:post_list' %}">Blog.</a>  
                </p>
        </div>
        <div id="explore-col" class="col-md-4">
            <a href="{% url  'blog:book_list' %}"><h3>Books</h3></a> 
                <p>If you would like to explore a beautiful list of some of the books I have read, head over to 
                    the <a href="{% url 'blog:book_list' %}">Books page.</a>  
                </p>       
        </div>
        <div id="explore-col" class="col-md-4">
            <a href="{% url  'blog:knowledge_repo' %}"><h3>Knowledge Table</h3></a> 
            <p>If you are looking for a reference list of helpful articles and information
                sources on various topics you should head over to the <a href="{% url 'blog:knowledge_repo' %}">Knowledge Table.</a>  
            </p>
        </div>
        <div id="explore-col" class="col-md-4">
            <a href="{% url  'scrapey:post_list' %}"><h3>Outside Articles</h3></a> 
            <p> If you would like to browse through an a list of external articles on various topics
                that I've aggregated and continually update then head to the 
                <a href="{% url  'scrapey:post_list' %}">Blog-External page</a>  
            </p>
        </div>
        <div id="explore-col" class="col-md-4">
            <a href="{% url  'blog:questions' %}"><h3>Questions</h3></a> 
            <p>If you would like to help me understand the world better, then check out
               the <a href="{% url 'blog:questions' %}">Questions</a>  page to see the topics that I'm  
               searching for answers on. 
            </p>
        </div>        
    </div>

{% endblock %}

MySite/blog/templates/blog/knowledge_repo.html
{% extends "blog/base.html" %}

{% block title %}FunWithBrandt-KnowledgeRepo{% endblock %}
{% block styles %}
    <style>    
    </style>
{% endblock %} 

{% block content %}


    <h2>Knowledge Repository</h2>
    <br />
    <p>
        My beautiful table of learning. I would love additional entries so hit me up with other sources.
        This needs heavy refining. At the very least I need much better descriptions. Clicking on a tag is 
        equivalent to searching that term in the search box.
    </p>



    <form method="get">
        <div class="form-group">
            <div class="input-group">
                <input id="searchBox" type="search" class="search" name="search_box"/>
                <button class="btn btn-secondary btn-sm">
                    <span class="glypicon glyphicon-search"></span>Search
                </button>
            </div>
        </div>
    </form>

    <table class="table table-responsive table-striped table-bordered table-hover table-sm">
      
        <thead>
            <tr>
                <th>Person/Institution</th>
                <th>Description</th>
                <th>Tags</th>
            </tr>
        </thead>
        
        <tbody>
            {% for knowledge in knowledge_list %}
                <tr>
                    <td>{{ knowledge.author }}</td>
                    <td><a href="{{ knowledge.source }}">{{ knowledge.description }}</a></td>
                    <td>
                        <form method="get">
                            {% for tag in knowledge.tags_as_list %}
                                <button class="badge badge-primary" name="search_box" value="{{ tag }}" style="margin-bottom: 2px;">
                                    {{ tag }}
                                </button>
                            {% endfor %}
                        </form>
                       
                        <!-- btn btn-primary btn-sm -->
                    </td>
                </tr>
            {% endfor %}
        </tbody>


    </table>

{% endblock %}

MySite/blog/templates/blog/questions.html
{% extends "blog/base.html" %}

{% block title %}FunWithBrandt-Questions{% endblock %}
{% block styles %}
    <style>    
    </style>
{% endblock %} 

{% block content %}


    <h2>Questions</h2>
    <br />
    <p>
        Here is a list of questions and topics on things that either I don’t understand, or on things that
        I want to understand much better. If you can add some insight here or point me in the right direction, 
        please hit me up : 225-907-4265.
    </p>
    <br>
    <!-- <form method="get">
        <div class="form-group">
            <div class="input-group">
                <input id="searchBox" type="search" class="search" name="search_box"/>
                <button class="btn btn-secondary btn-sm">
                    <span class="glypicon glyphicon-search"></span>Search
                </button>
            </div>
        </div>
    </form> -->

        <ul>
            {% for question in questions %}
                <li>{{ question.question }}</li>
            {% endfor %}
        </ul>
        

{% endblock %}